#!/bin/sh

# run test
deno test -A --unstable --import-map=./import_map.json

# format the code and commit it
deno fmt
git add .
git diff --quiet && git diff --staged --quiet || git commit -m "format"
