name: CI
on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  deploy:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
    name: test
    steps:
      - uses: actions/checkout@master
      - name: Setup Deno
        uses: denoland/setup-deno@main
        with:
          deno-version: v1.x
      - name: Test
        run: deno test -A --unstable --import-map=./import_map.json
